### ISSUE TITLE
NPM version 1.7.23 can't load DOCS

### ISSUE THREAD

**Issue by yehormasalitin** [graphql/graphql-playground#1218] opened 2020-05-29 13:59 UTC
#### This issue pertains to the following package(s):

- [x] GraphQL Playground HTML
- [x] GraphQL Playground

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?

https://www.npmjs.com/package/graphql-playground-react

#### What is the expected behavior?

DOCS should be loaded (works on 1.7.22)
![image](https://user-images.githubusercontent.com/6221420/83267944-98ac0780-a1cd-11ea-81a9-b3f15bb86103.png)

#### What is the actual behavior?

DOCS are not loading (showing loading animation over and over again)
![image](https://user-images.githubusercontent.com/6221420/83267995-a82b5080-a1cd-11ea-968a-4d3789036533.png)

#### What steps may we take to reproduce the behavior?
Update version to 1.7.23

_Please provide a gif or image of the issue for a quicker response/fix._

I downgraded to 1.7.22, and it is working again

**Comment by yoshiakis** [comment] 2020-10-19 13:57
Could you see error messages on the browser console? I can't reproduce this error on my local environment.

**Comment by acao** [comment] 2020-10-20 20:16
I think this is a duplicate of a bug that was already resolved

**Closed** 2022-04-19 14:31 UTC
