### ISSUE TITLE
GraphQL Playground Server Cannot Be Reached Running Locally

### ISSUE THREAD

**Issue by tpage99** [graphql/graphql-playground#877] opened 2018-10-31 04:19 UTC
#### This issue pertains to the following package(s):

- [x] GraphQL Playground

#### What OS and OS version are you experiencing the issue(s) on?
Windows 10

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
2.16.7

#### What is the expected behavior?
Following [How to GraphQL Node tutorial](https://www.howtographql.com/graphql-js/5-connecting-server-and-database/) and on Connecting Server and Database with Prisma Bindings. 

On step "Accessing both GraphQL APIs inside the same Playground". After running ```node src/index.js``` in hackernews-node folder to start and opening separate terminal for ```graphql playground``` anticipating being able to work with both GraphQL APIs side-by-side.

#### What is the actual behavior?
Playground opens up and can access database GraphQL API but app GraphQL API says "Server cannot be reached" and "error": "Failed to fetch schema. Please check your connection" Terminal has no errors and says I'm running locally on 4000 for app and playground on localhost 3000/playground. 

#### What steps may we take to reproduce the behavior?
Run node project locally and then GraphQL playground. I've uploaded my current code to my repositories under GraphQL-Node.

_Please provide a gif or image of the issue for a quicker response/fix._
<img width="960" alt="graphql-serverissue" src="https://user-images.githubusercontent.com/33505741/47765793-b2a40200-dc99-11e8-9479-f702eece9063.PNG">

**Comment by baninaveen** [comment] 2018-11-01 07:08
I am getting same issue

**Comment by kimobrian** [comment] 2018-12-07 00:49
This happens when I open a new tab in playground

**Comment by joanprimpratrec2** [comment] 2018-12-28 07:20
Ok, in my case,  I just read the chrome developer console and it was an error with CORS, I had in .env the front end url running on a different port than the actual port.

**Comment by DarkEye123** [comment] 2019-01-23 10:32
@joanprimpratrec2 thank you! same for me

for newcomers -> check your server.start() method an d add playground into that
in my case 
`process.env.PLAYGROUND_URL === "http://localhost:3000"`

```
server.start(
  {
    cors: { credentials: true, origin: [process.env.FRONTEND_URL, process.env.BACKED_URL, process.env.PLAYGROUND_URL] },
  }, ....
);
```

**Comment by luillyfe** [comment] 2019-04-16 21:09
Also **examine carefully your apollo config**. It turns out in my case I was missing an `import` to my API (datasource)

**Comment by BengBu-YueZhang** [comment] 2019-04-22 05:47
me to

**Comment by michaelkargl** [comment] 2020-03-17 16:34
Just as I am having the same issue, did you ever find out what the problem was?

**Comment by adampwright** [comment] 2020-04-18 03:19
Same issue

**Comment by WSINTRA** [comment] 2020-05-12 23:46
I was having a similar error when using graphQL playground after following the howtographql tutorial. In the end it was trivial.
If I used localhost:4000 in my browser I got Server cannot be reached in the playground, 
the playground was also giving me strange errors when I tried using an Authorization headers, 
``
"error": "Unexpected token < in JSON at position 0"
``
or another one was,
``
Failed to execute 'fetch' on 'Window': Value is not a valid ByteString
``
I say its trivial because when I tried using the localhost ip in the browser 127.0.0.1:4000 
it worked without a hitch.

**Comment by hannahatwork** [comment] 2020-06-04 20:57
@WSINTRA your solution worked for me — thanks for sharing. seems like a bug; should it be reported separately?

**Comment by siminmaleki** [comment] 2020-06-05 00:56
I'm having the same problem. I tried to change the port from 4000 to something else. Also tried using 127.0.0.1 instead of localhost ... but none of them worked for me and I still receive the same error for different URLs : 
error": "Failed to execute 'fetch' on 'Window': Failed to parse URL from http://localhost: 4000/graphql"

**Comment by Praveen82** [comment] 2020-06-19 12:33
I am also facing same issue. Please let me know how to solve

**Comment by Praveen82** [comment] 2020-06-19 12:34
Facing same issue
http://localhost:8080/graphql

Server cannot be reached


{
  "error": "Failed to fetch schema. Please check your connection"
}

**Comment by mohamedsahel** [comment] 2020-06-29 12:53
same issue .. :(

**Comment by fredele20** [comment] 2020-07-09 01:02
I have similar problem using golang, please I need your help.

**Comment by Darthmaul** [comment] 2020-07-12 15:55
I have discovered I can receive this error when my `schema.graphql` has an error in it. One more thing to validate when checking this bug :)

**Comment by ddebrunner** [comment] 2020-07-17 14:15
It's failing for my situation accessing localhost because the `Host` header I set in HTTP Headers is being overwritten when the HTTP request is made. 

Other headers I set are getting though, but at least the Host header is being overridden, the server receives `Host: localhost:8080` rather than `Host: www.example.com`.

Using 1.8.10 IDE.

**Comment by micksp** [comment] 2020-08-09 09:54
In my case the mistake was clear in the server logging. Entries like ```[2020-08-09 09:38:36] local.ERROR: Type User not found.``` gave me an indication where to look. The message in de playground 'server cannot be reached' however puts you on the wrong track.

**Comment by chocodamo** [comment] 2020-09-04 01:23
This has been open since 2018, wow. Anyhow, this might work to anyone with a similar issue...

I'm assuming a lot here, but based on your first screenshot, at the bottom you have an __authentication_ token_, which probably was created dynamically (based on a login, perhaps), so the server is trying to sign in with an old token, if it so... well, there is the problem, just remove it, go fetch a fresh one, then type it back. Now you should be online and able to query. 
Had a similar problem today.

**Comment by hankdevops** [comment] 2020-09-17 06:17
The authentication token that I had had an expiry date of 2021. Simply tried deleting the token and still, the same thing happens.

**Comment by m2paulc** [comment] 2020-09-22 07:33
I too have the same issue. 
"server cannot be reached"
"error": "Unexpected token < in JSON at position 0"

What worked for me is replacing localhost with 127.0.0.1 and finally got a connection. Don't forget to include the port number as well as the target url. ex: http://127.0.0.1:3000/graphql

**Comment by sudeshdws** [comment] 2020-10-11 14:03
Use this dependency combination  below  in your pom file  then you will not get any error :  

                <dependency> 
			<groupId>com.graphql-java-kickstart</groupId>
			<artifactId>graphql-spring-boot-starter</artifactId>
			<version>5.10.0</version>
		</dependency>

		<dependency>
			<groupId>com.graphql-java-kickstart</groupId>
			<artifactId>playground-spring-boot-starter</artifactId>
			<version>5.10.0</version>
		</dependency>

**Comment by pratimagautam977** [comment] 2020-12-11 16:02
@tpage99 The URL you have entered is missing a colon after the localhost. Hope it helps!

**Comment by DivekJohns** [comment] 2021-05-01 07:20
in my case i had given **PARSE_SERVER_GRAPHQL_PATH=graphql** instead of  **PARSE_SERVER_GRAPHQL_PATH=/graphql** and  an missing slash spoiled my day

**Comment by DeanHarber** [comment] 2021-05-06 09:35
Posting to maybe save other people some time. Another piece of software was listening on port 4000 on my machine. 🤦

**Comment by Neelaka-Rupun** [comment] 2021-06-02 23:53
This issue is related with the server listing port. make sure that the server listing port is same in the playground listening port .

**Comment by dongorous** [comment] 2021-06-04 07:04
Tried all all solutions above but still not working on windows
![image](https://user-images.githubusercontent.com/16795098/120759812-fe9c3f00-c545-11eb-8cc2-2d02180a74b1.png)

**Comment by Neelaka-Rupun** [comment] 2021-06-04 10:13
@dongorous your sever listing port and the playground port same ?

**Comment by HudsonSchumaker** [comment] 2021-06-25 09:15
I am having this issue. is this related to the CORS or not?

**Comment by HudsonSchumaker** [comment] 2021-06-25 09:48
Used both and still not working. Used the latest version 11.1.0

**Comment by HudsonSchumaker** [comment] 2021-06-25 09:48
> Use this dependency combination below in your pom file then you will not get any error :
> 
> ```
>             <dependency> 
> 		<groupId>com.graphql-java-kickstart</groupId>
> 		<artifactId>graphql-spring-boot-starter</artifactId>
> 		<version>5.10.0</version>
> 	</dependency>
> 
> 	<dependency>
> 		<groupId>com.graphql-java-kickstart</groupId>
> 		<artifactId>playground-spring-boot-starter</artifactId>
> 		<version>5.10.0</version>
> 	</dependency>
> ```

Used both and still not working. Used the latest version 11.1.0

**Comment by manojap** [comment] 2021-07-24 18:51
tried cors but no effect

**Comment by HudsonSchumaker** [comment] 2021-07-26 12:41
> tried cors but no effect

I just gave up and started to postman and is working

**Comment by manojap** [comment] 2021-07-26 15:23
I found a solution for Nextjs , here is the gits link, may be it work for you, it work for me.
https://gist.github.com/manojap/9ce06efffec89aa47bac962c7d11ef75

**Comment by manojap** [comment] 2021-07-27 03:54
I added a gists that may help you
MANOJ AP
GitHub <https://github.com/manojap>

**Comment by hanhaiszw** [comment] 2021-08-28 04:10
Same issue, tried cors but no effect

**Comment by SuperCipher** [comment] 2021-09-18 11:18
Make sure you have `http://` in front of your domain name as well.

**Comment by acao** [comment] 2021-09-18 11:44
Closing this, as it is a very obtuse support issue and seems to be causing confusion. These issues might be caused by:

- not handling CORS preflight requests in the server properly, which are required for cross origin POST
- your server not starting or failing to handle graphql requests
- incorrect server url
- an issue with the oss server library or framework‘s implementation of playground

We will be introducing a schema validation feature which will make a very small dent in these cases, and which will surface error payloads from your server finally!

if you have other support issues you can join our discord! https://discord.gg/HWRgmEF8Q5

**Closed by acao** 2021-09-18 11:44 UTC
Labels: bug/2-confirmed, kind/bug

**Comment by acao** [comment] 2021-09-18 11:49
@manojap that seems to be related to the apollo graphql playground which is a fork of this repository, we do not support the apollo fork sorry!

**Comment by rahulChefkart** [comment] 2021-09-30 14:53
Having the same issue in macOs.
![Screenshot 2021-09-30 at 8 21 20 PM](https://user-images.githubusercontent.com/87324339/135478744-5063cb80-eb75-40ff-997b-fa9db51e6f33.png)

**Comment by rahulChefkart** [comment] 2021-09-30 14:55
Having the same issue on MacOS.
![Screenshot 2021-09-30 at 8 24 27 PM](https://user-images.githubusercontent.com/87324339/135479386-6bc7fa60-a73a-4948-9a22-754470228be9.png)

**Comment by akinncar** [comment] 2021-11-12 22:48
For me I had some problems with my mutations declaration, I recommend you to try to run your graphql on some other platform like insomnia to find the problem.

**Comment by dmathewwws** [comment] 2021-11-17 00:46
I was running into this same problem, and using Apollo server where on production I would get the error. 

Followed the advice on https://github.com/graphql/graphql-playground/issues/876 and set `introspection:true` and it worked great. (its defaulted to False when NODE_ENV is production for Apollo Server)

**Comment by wanjuntham** [comment] 2021-11-24 12:27
*Just to keep a note for future self and others*

When `NODE_ENV` is set to `production`, the boolean value of [`playground`](https://www.apollographql.com/docs/apollo-server/v2/api/apollo-server/#playground) and [`introspection`](https://www.apollographql.com/docs/apollo-server/v2/api/apollo-server/#introspection) will be set to `false`.

Please make sure these values are set to `true` explicitly.

**Comment by RezaHabibi1001** [comment] 2022-03-10 04:36
> 

you should check your URL   ,  if it is written correct or wrong

**Comment by jiapei100** [comment] 2022-06-05 10:12
Is there a conclusion for this issue???
Thanks ...

**Comment by jiapei100** [comment] 2022-06-06 06:25
> I found a solution for Nextjs , here is the gits link, may be it work for you, it work for me. https://gist.github.com/manojap/9ce06efffec89aa47bac962c7d11ef75

Gone????

**Comment by sheikx1221** [comment] 2022-07-14 15:05
I was using nestJs and added cors true in graphql forRoot options but that didn't worked out and after 2-3 refresh the playground could no longer connect with GraphQL API

Then I added the following code into main.ts where you bootstrap your Nest application
`  const app = await NestFactory.create(AppModule, { cors: {
    credentials: true, origin: ['http://localhost:3000']
  }});`

This solved the issue and now the playground can connect with the GraphQL API

**Comment by Nditah** [comment] 2022-09-22 13:55
None of the suggested solutions works for me. I using @nestjs

**Comment by shonmorgun** [comment] 2022-11-20 23:21
Set `crossOriginEmbedderPolicy` in `helmet` properties to `false` will fix this problem. Like so:
```
server.use(helmet({
    crossOriginEmbedderPolicy: false
}));
```

**Comment by SOMONSOUM** [comment] 2023-01-20 10:02
> _Just to keep a note for future self and others_
> 
> When `NODE_ENV` is set to `production`, the boolean value of [`playground`](https://www.apollographql.com/docs/apollo-server/v2/api/apollo-server/#playground) and [`introspection`](https://www.apollographql.com/docs/apollo-server/v2/api/apollo-server/#introspection) will be set to `false`.
> 
> Please make sure these values are set to `true` explicitly.

This solution will work for those who use Apollo Server V3

**Comment by shadab14meb346** [comment] 2023-02-11 10:22
For me, I was running graphql using `serverless offline` and due to the node version being not less than 15 I was getting not able to connect to the server error.[ Here's](https://github.com/dherault/serverless-offline/issues/1150) the detailed discussion about it

**Comment by JOSEPHOMOTOSHO** [comment] 2023-03-19 03:47
GraphQLModule.forRoot({
      autoSchemaFile: `schema.gql`,
      driver: ApolloDriver,
      playground: true,
      endpoint:"/graphql",
      introspection:true
    }),
    
    adding instropection:true did it for me
